
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CIRCLE COMMA CONNECT DRAW EQUAL HEIGHT LPAREN NUMBER POINT RECTANGLE RPAREN SIZE SQUARE START TRIANGLE WEIGHT WORDS\n    draw_conn : DRAW SQUARE\n        | DRAW SQUARE SIZE EQUAL NUMBER\n        | DRAW SQUARE START LPAREN NUMBER COMMA NUMBER RPAREN\n        | DRAW SQUARE START LPAREN NUMBER COMMA NUMBER RPAREN AND SIZE EQUAL NUMBER\n        | DRAW CIRCLE\n        | DRAW CIRCLE SIZE EQUAL NUMBER\n        | DRAW CIRCLE START LPAREN NUMBER COMMA NUMBER RPAREN\n        | DRAW CIRCLE START LPAREN NUMBER COMMA NUMBER RPAREN AND SIZE EQUAL NUMBER\n        | DRAW RECTANGLE\n        | DRAW RECTANGLE HEIGHT EQUAL NUMBER AND WEIGHT EQUAL NUMBER\n        | DRAW RECTANGLE START LPAREN NUMBER COMMA NUMBER RPAREN\n        | DRAW RECTANGLE START LPAREN NUMBER COMMA NUMBER RPAREN AND HEIGHT EQUAL NUMBER AND WEIGHT EQUAL NUMBER\n        | CONNECT conn AND conn\n        | CONNECT conn AND conn AND conn\n        | CONNECT conn AND conn AND conn AND conn\n        | CONNECT conn AND conn AND conn AND conn AND conn\n        | CONNECT conn AND conn AND conn AND conn AND conn AND conn\n        | CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn\n        | CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn\n        | CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn\n        | CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn\n    \n    conn : POINT LPAREN NUMBER COMMA NUMBER RPAREN\n    \n    square : SQUARE\n    \n    circle : CIRCLE\n    \n    rect : RECTANGLE\n    '
    
_lr_action_items = {'DRAW':([0,],[2,]),'CONNECT':([0,],[3,]),'$end':([1,4,5,6,23,25,27,37,44,45,46,48,49,52,58,63,64,66,70,73,74,76,78,],[0,-1,-5,-9,-13,-2,-6,-14,-22,-3,-7,-11,-15,-10,-16,-4,-8,-17,-18,-12,-19,-20,-21,]),'SQUARE':([2,],[4,]),'CIRCLE':([2,],[5,]),'RECTANGLE':([2,],[6,]),'POINT':([3,15,31,43,54,62,68,72,75,77,],[8,8,8,8,8,8,8,8,8,8,]),'SIZE':([4,5,50,51,],[9,11,55,56,]),'START':([4,5,6,],[10,12,14,]),'HEIGHT':([6,53,],[13,57,]),'AND':([7,23,29,37,44,45,46,48,49,58,65,66,70,74,76,],[15,31,35,43,-22,50,51,53,54,62,67,68,72,75,77,]),'LPAREN':([8,10,12,14,],[16,18,20,22,]),'EQUAL':([9,11,13,41,55,56,57,69,],[17,19,21,47,59,60,61,71,]),'NUMBER':([16,17,18,19,20,21,22,32,33,34,36,47,59,60,61,71,],[24,25,26,27,28,29,30,38,39,40,42,52,63,64,65,73,]),'COMMA':([24,26,28,30,],[32,33,34,36,]),'WEIGHT':([35,67,],[41,69,]),'RPAREN':([38,39,40,42,],[44,45,46,48,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'draw_conn':([0,],[1,]),'conn':([3,15,31,43,54,62,68,72,75,77,],[7,23,37,49,58,66,70,74,76,78,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> draw_conn","S'",1,None,None,None),
  ('draw_conn -> DRAW SQUARE','draw_conn',2,'p_draw_conn','A_sintatico.py',12),
  ('draw_conn -> DRAW SQUARE SIZE EQUAL NUMBER','draw_conn',5,'p_draw_conn','A_sintatico.py',13),
  ('draw_conn -> DRAW SQUARE START LPAREN NUMBER COMMA NUMBER RPAREN','draw_conn',8,'p_draw_conn','A_sintatico.py',14),
  ('draw_conn -> DRAW SQUARE START LPAREN NUMBER COMMA NUMBER RPAREN AND SIZE EQUAL NUMBER','draw_conn',12,'p_draw_conn','A_sintatico.py',15),
  ('draw_conn -> DRAW CIRCLE','draw_conn',2,'p_draw_conn','A_sintatico.py',16),
  ('draw_conn -> DRAW CIRCLE SIZE EQUAL NUMBER','draw_conn',5,'p_draw_conn','A_sintatico.py',17),
  ('draw_conn -> DRAW CIRCLE START LPAREN NUMBER COMMA NUMBER RPAREN','draw_conn',8,'p_draw_conn','A_sintatico.py',18),
  ('draw_conn -> DRAW CIRCLE START LPAREN NUMBER COMMA NUMBER RPAREN AND SIZE EQUAL NUMBER','draw_conn',12,'p_draw_conn','A_sintatico.py',19),
  ('draw_conn -> DRAW RECTANGLE','draw_conn',2,'p_draw_conn','A_sintatico.py',20),
  ('draw_conn -> DRAW RECTANGLE HEIGHT EQUAL NUMBER AND WEIGHT EQUAL NUMBER','draw_conn',9,'p_draw_conn','A_sintatico.py',21),
  ('draw_conn -> DRAW RECTANGLE START LPAREN NUMBER COMMA NUMBER RPAREN','draw_conn',8,'p_draw_conn','A_sintatico.py',22),
  ('draw_conn -> DRAW RECTANGLE START LPAREN NUMBER COMMA NUMBER RPAREN AND HEIGHT EQUAL NUMBER AND WEIGHT EQUAL NUMBER','draw_conn',16,'p_draw_conn','A_sintatico.py',23),
  ('draw_conn -> CONNECT conn AND conn','draw_conn',4,'p_draw_conn','A_sintatico.py',24),
  ('draw_conn -> CONNECT conn AND conn AND conn','draw_conn',6,'p_draw_conn','A_sintatico.py',25),
  ('draw_conn -> CONNECT conn AND conn AND conn AND conn','draw_conn',8,'p_draw_conn','A_sintatico.py',26),
  ('draw_conn -> CONNECT conn AND conn AND conn AND conn AND conn','draw_conn',10,'p_draw_conn','A_sintatico.py',27),
  ('draw_conn -> CONNECT conn AND conn AND conn AND conn AND conn AND conn','draw_conn',12,'p_draw_conn','A_sintatico.py',28),
  ('draw_conn -> CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn','draw_conn',14,'p_draw_conn','A_sintatico.py',29),
  ('draw_conn -> CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn','draw_conn',16,'p_draw_conn','A_sintatico.py',30),
  ('draw_conn -> CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn','draw_conn',18,'p_draw_conn','A_sintatico.py',31),
  ('draw_conn -> CONNECT conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn AND conn','draw_conn',20,'p_draw_conn','A_sintatico.py',32),
  ('conn -> POINT LPAREN NUMBER COMMA NUMBER RPAREN','conn',6,'p_conn','A_sintatico.py',49),
  ('square -> SQUARE','square',1,'p_SQUARE','A_sintatico.py',58),
  ('circle -> CIRCLE','circle',1,'p_CIRCLE','A_sintatico.py',76),
  ('rect -> RECTANGLE','rect',1,'p_RECTANGLE','A_sintatico.py',94),
]
